---
- name: phpenv依赖安装
  yum: name={{ item }} state=present
  with_items:
    - libtool
    - libtool-ltdl-devel
    - libtool-ltdl
    - libxml2-devel
    - bison
    - bison-devel
    - openssl-devel
    - curl-devel
    - libjpeg-devel
    - libpng-devel
    - readline-devel
    - libtidy-devel
    - libxslt-devel
    - httpd-devel
    - enchant-devel
    - libXpm
    - libXpm-devel
    - freetype-devel
    - t1lib
    - t1lib-devel
    - gmp-devel
    - libc-client-devel
    - libicu-devel
    - oniguruma-devel
    - net-snmp
    - net-snmp-devel
    - bzip2-devel
    - postgresql-devel
- name: libmcrypt
  yum: name={{ item }} state=present enablerepo=epel
  with_items:
    - re2c
    - libmcrypt
    - libmcrypt-devel
- name: phpenv确认
  command: ls /usr/local/share/phpenv
  register: result
  ignore_errors: true
- name: CHH/phpenv Download
  command: git clone -b master git://github.com/CHH/phpenv.git /usr/local/src/phpenv
  when: result|failed
- name: PHPENV_ROOT 执行
  raw: PHPENV_ROOT=/usr/local/share/phpenv /usr/local/src/phpenv/bin/phpenv-install.sh
  when: result|failed
- name: plugins目录生成
  file: path=/usr/local/share/phpenv/plugins force=yes state=directory
- name: php-build 插件下载
  command: git clone git://github.com/php-build/php-build.git /usr/local/share/phpenv/plugins/php-build
  when: result|failed
- name: default_configure_options 默认PHP编译配置
  copy: src=default_configure_options dest=/usr/local/share/phpenv/plugins/php-build/share/php-build/default_configure_options
- name: mysql.sock mysql.ini配置
  ignore_errors: true
  copy: src=mysql.ini dest=/usr/local/share/phpenv/versions/{{ php_version }}/etc/conf.d/mysql.ini
- name: timezone.ini配置
  ignore_errors: true
  copy: src=timezone.ini dest=/usr/local/share/phpenv/versions/{{ php_version }}/etc/conf.d/timezone.ini
